### ISSUE TITLE
1.0.1 $auth service not working

### ISSUE THREAD

**Issue by sebakerckhof** [Urigo/angular-meteor-auth#16]
I upgraded to angular-meteor-auth 1.0.1, but the $auth service does not seem to work.

I have a piece of code like this:
```js
resolve: {
        "currentUser": ["$auth", function($auth){
          return $auth.requireValidUser(user => user.managesInstitute);
        }]
      }
```

Which doesn't work, if I step into the code I get up to this line:
https://github.com/Urigo/angular-meteor-auth/blob/master/src/angular-meteor-auth.js#L134

however, `$rootScope[k]` does not exist. I.e. it does not have $requireValidUser, $requireUser or $awaitUser defined on it.

**Comment by DAB0mB** [comment]
@sebakerckhof I tested it using angular-meteor@1.3.9 and anglar-meteor-auth@1.0.1 and it seemed to work. Which version of angular-meteor are you using? In addition if you can provide a repository which can recreate the issue this would be very helpful.

**Comment by sebakerckhof** [comment]
Nevermind, turned out my angular module dependencies were wrongly specified, so the Mixer function (https://github.com/Urigo/angular-meteor-auth/blob/master/src/angular-meteor-auth.js#L143) ran after my route was triggered. 

Anyway, learned a lot about meteor-angular internals debugging this. It's quite creative :)
