### ISSUE TITLE
improvement suggestion:awaitUser to resolve user immediately when user logged in 

### ISSUE THREAD

**Issue by mattiLeBlanc** [Urigo/angular-meteor-auth#25]
Hi,

On line 120 of angular-meteor-auth.js you do an autorun, which will check if the user is logged in.
It looks it always requires an extra cycle to check, even if a user is already logged in.

I will give an example where I run into this issue:

I have set up a $stateChangeStart event handler that checks if certain paths/state are allowed.
On that is NOT allowed is to go to login, when you are already logged in.

So I have the following 2 scenario's:

1 ) I am logged and setting in my dashboard. I state change to /login via ui-sref of ui-router and then the $stateChangeEvent executes. Because I am already logged in, I USED to use 

```
if ( Meteor.user() ) {
      let states: Array<string> = [ 'public.auth.login', 'public.auth.register', 'public.login.recovery' ];
      if ( _.includes( states, toStateName ) ) {

        event.preventDefault();

        this.$state.go( 'private.dashboard.open' );
      }
}
```

This will force the user to the dashboard instead of going to the login, when we are already logged in.

HOWEVER, this doesn't work if I go to the login page by changing the url in the browser manually.
Then, the Meteor.user() check will be undefined, and the force redirect will not occur.

So, to circumvent this I decided to use the `awaitUser` construct.

This, works fine, however in the $stateChangeStart handler, it will run 2 times. The first time the user is not resolved (while I am already logged in) and it will try to go to the login page.
Then it runs again and it CAN actually execute the event.preventDefault.

Is it possible, to resolve the promise right away when awaitUser is called so that I do not get 2 cycles in which my UI state flashes from one state to the other?

EDIT: my solution seems to work in my local version of your package.

```

 $$Auth.$awaitUser = function (validate) {
      var _this = this;

      validate = validate ? this.$bindToContext($Mixer.caller, validate) : function () {
        return true;
      };

      if (!_.isFunction(validate)) {
        throw Error('argument 1 must be a function');
      }

      var deferred = this.$$defer();

     // Resolve promise immediately if user exists
     //
      if ( _this.currentUser ) {
         deferred.resolve( _this.currentUser );
         return deferred.promise;
      }

      // Note the promise is being fulfilled in the next event loop to avoid
      // nested computations, otherwise the outer computation will cancel the
      // inner one once the scope has been destroyed which will lead to subscription
      // failures. Happens mainly after resolving a route.
      var computation = this.autorun(function (computation) {
        if (_this.getReactively('isLoggingIn')) return;
        // Stop computation once a user has logged in
        computation.stop();

        if (!_this.currentUser) return _this.$$afterFlush(deferred.reject, errors.required);

        var isValid = validate(_this.currentUser);
        // Resolve the promise if validation has passed
        if (isValid === true) return _this.$$afterFlush(deferred.resolve, _this.currentUser);

        var error = void 0;

        if (_.isString(isValid) || isValid instanceof Error) {
          error = isValid;
        } else {
          error = errors.forbidden;
        }

        return _this.$$afterFlush(deferred.reject, error);
      });

      var promise = deferred.promise;
      promise.stop = computation.stop.bind(computation);
      return promise;
    };

```

**Comment by mattiLeBlanc** [comment]
@Urigo I this something that still has value?

**Comment by DAB0mB** [comment]
@mattiLeBlanc It is relevant indeed, what I am afraid of is that it would be a breaking change since some implementations might rely on the `stop()` method we bind to the returned promise, we will need to think of a proper solution that won't break any app.

**Comment by mattiLeBlanc** [comment]
We could still do something like this
```
let promise =  deferred.promise;
promise.stop = null;
deferred.resolve( _this.currentUser );
return promise;
```

Or maybe make `promise.stop` an empty function?

**Comment by Urigo** [comment]
@mattiLeBlanc closing with the new version, let me know if it works for you

**Comment by mattiLeBlanc** [comment]
great! Thanks for integrating this. Code looks good, should work.
