### ISSUE TITLE
$auth.currentUser in router

### ISSUE THREAD

**Issue by santiq** [Urigo/angular-meteor-auth#26]
Hi!
I need to allow users to enter in my login page only if is  there is no logged user

 ```
.state('login', {
    url: '/login',
    templateUrl: 'client/views/login.html',
    controller: 'loginController',
    controllerAs: 'login',
    resolve: {
      user: ($auth) => { console.log($auth)
        if ($auth.currentUser) {
          return 'ALREADY_LOGGED';
        }
        return true;
      }
    }
  })
```

But `$auth` doens't have the propertie `currentUser`

![screen shot 2016-06-01 at 13 02 14](https://cloud.githubusercontent.com/assets/7070683/15716564/3029186c-27f9-11e6-92cf-15fb60b3d17f.png)

**Comment by sinr0202** [comment]
@santiq: In the document (https://www.angular-meteor.com/api/1.3.2/auth) it says to resolve using $auth.requireUser()

**Comment by DAB0mB** [comment]
@santiq Like said above, you will need to invoke a method called `awaitUser()` which will be invoked with a function receiving the current logged in user, where you can decide to either resolve the promise or reject it by returning true or false, exactly like your handler. More information can be found [here](https://www.angular-meteor.com/api/1.3.11/auth). In addition, once the route has been resolved and you've reached the controller, the scope will have a property called `currentUser` just like you expected which will determine whether the user is logged in or not. Hopefully this helps. Would like to hear your response.
