### ISSUE TITLE
bower.json dependency

### ISSUE THREAD

**Issue by jchiotaka** [Urigo/angular-meteor-auth#6]
I tried to install angular-meteor-auth via bower and it requires "angular-meteor": "1.4.0" but latest release of angular-meteor on GitHub is 1.3.7

**Comment by rdeift** [comment]
+1

**Comment by dmendoza** [comment]
+1

**Comment by davelab** [comment]
+1

**Comment by tulumario** [comment]
+1

**Comment by tulumario** [comment]
you can copy paste it to your project and in dependencies just change from 1.4.0 to 1.3.7. It works then...

**Comment by jchiotaka** [comment]
Sure that works for local development, but I don't want to commit he library and carry it over in my branch. I prefer to use it via bower.

**Comment by Urigo** [comment]
Hi everyone, sorry it took time but it should now be fixed.
You can use version `0.2.2` with any angular-meteor version higher than `1.3.0` or the recommended version `1.0.0` with the recommended `angular-meteor` version `1.3.9`.
Please let me know if it's working for you now.
